language: ruby

matrix:
  include:
    - env: OSX=10.11
      os: osx
      osx_image: osx10.11
      rvm: 2.7.1
    - env: OSX=10.10
      os: osx
      osx_image: xcode7
      rvm: 2.7.1
    - env: OSX=10.9
      os: osx
      osx_image: beta-xcode6.2
      rvm: 2.7.1
  allow_failures:
    - os: linux
      dist: bionic
      rvm: 2.7.1

env:
  global:
    - HOMEBREW_DEVELOPER=1
    - HOMEBREW_VERBOSE=1

before_install:
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
      export PATH="~/.linuxbrew/bin:~/.linuxbrew/sbin:$PATH";
      export HOME=/home/linuxbrew;
      export LINUXBREW=$HOME/.linuxbrew;
      export HOMEBREW_DEVELOPER=1
      export HOMEBREW_FORCE_VENDOR_RUBY=1
      export HOMEBREW_NO_AUTO_UPDATE=1
      sudo apt-get -qq update;
      sudo mkdir $HOME;
      sudo chown "$USER:" $HOME;
      mkdir $LINUXBREW;
      curl -L https://github.com/Linuxbrew/brew/tarball/master | tar xz -m --strip 1 -C $LINUXBREW;
    fi
  - brew update || brew update
  - if [ -f ".git/shallow" ]; then travis_retry git fetch --unshallow; fi
  - mkdir -p $(brew --repo)/Library/Taps/jebenexer
  - ln -s $PWD $(brew --repo)/Library/Taps/jebenexer/homebrew-nginx
  - cd $(brew --repo)/Library/Taps/jebenexer/homebrew-nginx
  - export TRAVIS_BUILD_DIR="$(brew --repo)/Library/Taps/jebenexer/homebrew-nginx"
  - ulimit -n 1024
  # Fix linux error: Incorrect file permissions (664)
  - chmod 0644 Formula/*.rb
  - umask 022

script:
  - brew test-bot
  #- if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then
  #    brew test-bot --ci-testing;
  #  else
  #    brew test-bot --ci-pr;
  #  fi

notifications:
  email: never
